views/login_manager.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from setup import services_listing as services
from views.decorators import setup_decorators
from views.decorators import inject_decorators

login_manager = Blueprint('login_manager', __name__, url_prefix='/authentication',
                          template_folder='templates')

@login_manager.route('/login', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
def login(login_service: services.USER_LOGIN):
    if request.method == "POST":
        if login_service.user_login(request.form['NameInput'],
                                    request.form['PasswordInput']) is True:
            return redirect(url_for("post_manager.index"))

        if login_service.flag_unset_password and 'logged_id' in session:
            return redirect(url_for("user_manager.reset_item",
                                    user_index=session['logged_id']))
        flash('Invalid login')
        return render_template("login_user.html")
    return render_template("login_user.html")

@login_manager.route('/logout', methods=["GET"])
@setup_decorators.config_check
@inject_decorators.inject
def logout(login_service: services.USER_LOGIN):
    login_service.user_logout()
    return redirect(url_for("post_manager.index"))

views/post_manager.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from setup import services_listing as services
from models.blog_post import BlogPost
from views.decorators import setup_decorators
from views.decorators import inject_decorators
from views.decorators import authorization_decorators

post_manager = Blueprint('post_manager', __name__, url_prefix='/posts',
                         template_folder='templates',
                         static_folder='static')

@post_manager.route('/', methods=["GET"])
@setup_decorators.config_check
@inject_decorators.inject
def index(current_users: services.DATA_SOURCE_USERS,
          current_database: services.DATA_SOURCE_POSTS,
          pagination_factory: services.PAGINATION_FACTORY):

    pagination = pagination_factory.create_pagination(current_database,
                                                      request.args.get("Users"),
                                                      request.args.get("Page"))
    return render_template("list_posts.html",
                           database=pagination,
                           users=current_users)

@post_manager.route('/<uuid:post_index>')
@setup_decorators.config_check
@inject_decorators.inject
def content(post_index,
            current: services.DATA_SOURCE_POSTS):
    return render_template("view_post.html",
                           current=current.get_by_id(post_index))

@post_manager.route('/add', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.requres_login
def add_item(current_database: services.DATA_SOURCE_POSTS):

    if request.method == "POST":
        to_add = BlogPost(
            request.form['NameInput'],
            session['logged_id'],
            request.form['ContentInput'],
            None)

        to_add.upload(request.files['Image-File'])

        current_database.add_post(to_add)
        return redirect(url_for('.content', post_index=to_add.post_id))
    return render_template("add_post.html")

@post_manager.route('/remove/<uuid:post_index>')
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.requres_login
@authorization_decorators.admin_or_owner_required
def remove_item(post_index,
                current_database: services.DATA_SOURCE_POSTS):
    current_database.remove(post_index)
    return redirect('/posts')

@post_manager.route('/update/<uuid:post_index>', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.requres_login
@authorization_decorators.admin_or_owner_required
def update_item(post_index,
                current_database: services.DATA_SOURCE_POSTS):

    if request.method == "GET":
        return render_template("update_post.html",
                               current=current_database.get_by_id(post_index))

    if request.method == "POST":
        current = current_database.get_by_id(post_index)

        current.update(request.form['NameInput'],
                       request.form['ContentInput'])

        current.upload(request.files['Image-File'])

        current_database.update_post(current,
                                     bool('Remove-Picture' in request.form),
                                     bool('Update-Picture' in request.form))

        return redirect(url_for('.content', post_index=current.post_id))
    return Exception("Request type cannot be handled")

views/statistics_manager.py
from flask import Blueprint, render_template, request
from setup import services_listing as services
from views.decorators import setup_decorators
from views.decorators import inject_decorators

stat_manager = Blueprint('statistics_manager',
                         __name__,
                         url_prefix='/user_statistics',
                         template_folder='templates')

@stat_manager.route('/', methods=["GET"])
@setup_decorators.config_check
@inject_decorators.inject
def user_statistics(user_stats: services.USER_STATISTICS,
                    current_users: services.DATA_SOURCE_USERS):
    user_stats = user_stats.get_statistics(request.args.get("Users"))
    return render_template('user_statistics.html', users=current_users, stats=user_stats)

views/user_manager.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from setup import services_listing as services
from models.user import User
from views.decorators import setup_decorators
from views.decorators import inject_decorators
from views.decorators import authorization_decorators

user_manager = Blueprint(
    'user_manager',
    __name__,
    url_prefix='/users',
    template_folder='templates')

@user_manager.route('/', methods=["GET"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_required
def index(current_database: services.DATA_SOURCE_USERS):
    return render_template("list_users.html", database=current_database.get_users())

@user_manager.route('/<uuid:user_index>')
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_or_owner_required
def content(user_index, current_database: services.DATA_SOURCE_USERS):
    return render_template("view_user.html", element=current_database.get_user_by_id(user_index))

@user_manager.route('/add', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_required
def add_item(current_database: services.DATA_SOURCE_USERS):
    if request.method == "POST":
        to_add = User(
            request.form['NameInput'],
            request.form['EmailInput'],
            request.form['PasswordInput'])
        current_database.add_user(to_add)
        return redirect(url_for('.content', user_index=to_add.user_id))
    return render_template("add_user.html")

@user_manager.route('/remove/<uuid:user_index>')
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_required
def remove_item(user_index, current_database: services.DATA_SOURCE_USERS):
    current_database.remove_user(user_index)
    return redirect('/users')

@user_manager.route('/update/<uuid:user_index>', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_or_owner_required
def update_item(user_index,
                current_database: services.DATA_SOURCE_USERS,
                login_manager: services.USER_LOGIN):
    if request.method == "GET":
        return render_template("update_user.html",
                               current=current_database.get_user_by_id(user_index))

    if request.method == "POST":
        current = current_database.get_user_by_id(user_index)
        current.update(request.form['UserNameInput'],
                       request.form['UserEmailInput'],
                       request.form['UserPassInput'])
        current_database.update_user(current)
        login_manager.login_update(current)
        return redirect(url_for('.content', user_index=current.user_id))
    return Exception("Request type cannot be handled")

@user_manager.route('/reset/<uuid:user_index>', methods=["GET", "POST"])
@setup_decorators.config_check
@inject_decorators.inject
@authorization_decorators.admin_or_owner_required
def reset_item(user_index,
               current_database: services.DATA_SOURCE_USERS,
               login_manager: services.USER_LOGIN):
    if request.method == "GET":
        return render_template("update_user.html",
                               current=current_database.get_user_by_id(user_index))

    if request.method == "POST":
        current = current_database.get_user_by_id(user_index)

        if not request.form['UserPassInput']:
            flash('Invalid password')
            return render_template("update_user.html",
                                   current=current_database.get_user_by_id(user_index))

        current.update(request.form['UserNameInput'],
                       request.form['UserEmailInput'],
                       request.form['UserPassInput'])
        login_manager.login_update(current)
        current_database.update_user(current)
        return redirect(url_for('user_manager.content', user_index=current.user_id))
    return Exception("Request type cannot be handled")

templates/add_post.html
{% extends "base_layout.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='add_update_style.css') }}" />
{% endblock %}

{% block body %}
    <div><h1 class="TitleField">Add Post</h1></div>
    <div class="form-group">
        <form method="post" enctype="multipart/form-data">
            <label typeof="string">Name : </label><br />
            <textarea class="TitleInput form-control" rows="1" name="NameInput"></textarea><br />
            <label typeof="string">Content : </label><br />
            <textarea class="ContentInput form-control" rows="10" name="ContentInput"></textarea><br /><br />
            <input type="file" name="Image-File">
            <button class="btn btn-default">Submit</button>
        </form>
    </div>
{% endblock %}

templates/add_user.html
{% extends "base_layout.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='base_form_style.css') }}" />
{% endblock %}

{% block body %}
<div class="Form">
    <header class="panel">
        <h3>Add new user: </h3>
    </header>
    <form method="post">
        <label typeof="string">Username</label><br />
        <textarea typeof="string" class="Form-Field form-control" rows="1" name="NameInput"></textarea><br />
        <label typeof="string">Email:</label><br />
        <textarea typeof="string" class="Form-Field form-control" rows="1" name="EmailInput"></textarea><br />
        <label typeof="string">Password</label><br />
        <input type="password" class="form-control" name="PasswordInput"><br />
        <button class="SubmitButton">Submit</button>
    </form>
</div>
{% endblock %}

templates/base_layout.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='base_layout_style.css') }}" />
    {% block head %} {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav mr-auto">
            <li class="nav-link"><a href="{{ url_for('post_manager.index')}}">Posts</a></li>
            {% if session['logged_name'] == 'admin' %}
            <li class="nav-link"><a href="{{ url_for('user_manager.index')}}">Users</a></li>
            {% endif %}
            <li class="nav-link"><a href="{{ url_for('statistics_manager.user_statistics')}}">Statistics</a></li>
            {% if session['logged_name'] is defined %}
            <li class="nav-link"><a href="{{ url_for('user_manager.update_item', user_index=session['logged_id'])}}">Edit User</a></li>
            {% endif %}
            {% if session['logged_name'] == 'admin' %}
            <li class="nav-link"><a href="{{ url_for('user_manager.add_item')}}">Add User</a></li>
            {% endif %}
            {% if session['logged_name'] is not defined %}
            <li class="nav-link"><a href="{{ url_for('login_manager.login') }}">Login</a></li>
            {% endif %}
            {% if session['logged_name'] is defined %}
            <li class="nav-link"><a href="{{ url_for('post_manager.add_item') }}">Add Post</a></li>
            <li class="nav-link"><a href="{{ url_for('login_manager.logout') }}">Logout</a></li>
            {% endif %}
        </ul>
    </nav>
    {% block body %}{% endblock %}
    <script type="text/javascript" src="{{ url_for('static', filename='scripts/script.js') }}"></script>
</body>
</html>

templates/list_posts.html
{% extends "base_layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='list_posts_style.css') }}" />
{% endblock %}

{% block body %}
<header class="MainHeader">
    <h1 class="MainTitle navbar-header">Blog App</h1>
</header>
    {% if session['logged_name'] is defined %}
<p>Logged in as: {{ session['logged_name'] }}</p>
    {% else %}
<p>Not logged in</p>
    {% endif %}
    <form method="get">
        <label for="Users">Select by User:</label>
        <select name="Users" class="form-control form-control-lg" id="users" onchange="this.form.submit()">
            <option>{{ 'None' }}</option>
            {% for user in users %}
                {% if user.user_name == request.args["Users"] %}
                    <option selected="selected">{{ user.user_name }}</option>
                {% else %}
                    <option>{{ user.user_name }}</option>
                {% endif %}
            {% endfor %}
        </select>
    </form>

    <div id="Posts-Listing">
        {% for post in database.get_page() %}
        <div class="container panel-body">
            <div class="headers">
                <h5>Post Title: {{ post.title }}</h5>
                <p>Post Author: {{ post.author }}</p>
                <p>Post Preview: {{ post.preview }}</p>
            </div>
            <div class="grid-item">
                <img src ="{{ post.img_path }}"class="thumbnail">
            </div>
            <div class="grid-item">
                <a class="btn btn-primary" href="{{ url_for('.content', post_index=post.post_id) }}">Go To Post</a>
            </div>
            <div class="grid-item">
                <small class="text-muted">Created on: {{ post.stamp.creation_time }}</small><br />
                {% if post.stamp.creation_time != post.stamp.edit_time %}
                <small class="text-muted">Last edited on: {{ post.stamp.edit_time }}</small>
                {% else %}
                <small class="text-muted">Never</small>
                {% endif %}
            </div>
        </div>
        <hr />
    </div>

        {% endfor %}
        <form method="get" name="Page" id="Page">
            <ul class="pagination pagination-sm">
                {% if database.can_previous() %}
                <li class="previous page-link"><a href="{{ url_for('.index', Users=request.args["Users"], Page=database.get_previous()) }}" onchange="this.form.submit()">Previous</a></li>
                {% endif %}
                {% if database.can_next() %}
                <li class="next page-link"><a href="{{ url_for('.index', Users=request.args["Users"], Page=database.get_next()) }}" onchange="this.form.submit()">Next</a></li>
                {% endif %}
            </ul>
        </form>
        <script type="text/javascript" src={{ url_for('static', filename='scripts/list_posts_script.js') }}></script>
{% endblock %}

templates/list_users.html
{% extends "base_layout.html" %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='list_users_style.css') }}" />
{% endblock %}

{% block body %}
<h3>Current registered users</h3>
    <div class="form-group">
        {% for element in database %}
        <div>
            <a href="{{ url_for('.content', user_index=element.user_id) }}" class="list-group-item">
                Username : {{ element.user_name }}<br />
                Email : {{ element.user_email }}
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/login_user.html
{% extends "base_layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_form_style.css') }}" />
{% endblock %}

{% block body %}
<div class="Form">
    <header class="panel">
        <h1>User Login: </h1>
    </header>
    <form method="post">
        <div class="form-group">
            <label for="username">Username</label>
            <input typeof="string" class="Form-Field form-control" id="username" name="NameInput">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="Form-Field form-control" id="password" name="PasswordInput">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p class="text-left">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% endblock %}
</div>

templates/setup.html
<!DOCTYPE html>

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='setup_style.css') }}" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
{% endblock %}

<body>
    <header class="panel">
        <h1>Connection Setup: </h1>
    </header>
    <form method="post">
        <div class="form-group">
            <label typeof="string">Host : </label><br />
            <div class="InputFields form-control"><input typeof="string" name="host" /> </div><br />
            <label typeof="string">Database : </label><br />
            <div class="InputFields form-control"><input typeof="string" name="database" /> </div><br />
            <label typeof="number">Port : </label><br />
            <div class="InputFields form-control"><input typeof="number" name="port" /></div><br />
            <label typeof="string">Username : </label><br />
            <div class="InputFields form-control"><input typeof="string" name="user" /> </div><br />
            <label typeof="password">Password : </label><br />
            <div class="InputFields form-control"><input type="password" name="password" /> </div><br />
            <button class="btn btn-default">Submit</button>
        </div>
    </form>
</body>

templates/unauthorized.html
<!DOCTYPE html>

<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width initial-scale=1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='base_layout_style.css') }}" />
</head>
<body>
    <h1>403 Unauthorized acces</h1>
    <form action="{{ error_redirect }}" method="post">
        <p>You tried to access a resource without appropriate credentials <br /> Please return to the homepage
        and provide appropriate credentials</p>
        <button class ="btn btn-primary" type="submit">Return to Homepage</button>
    </form>
</body>
</html>

templates/update_post.html
{% extends "base_layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='update_post_style.css') }}" />
{% endblock %}

{% block body %}
<br />
<div><h1 class="TitleField">Edit Post</h1></div>
<br />
<div>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p class="text-left">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
<div class="form-group">
    <form class="container" enctype="multipart/form-data" method="post">
        <div class="image-wrapper">
            <img src="{{ current.img_path }}"width="600" height="400">
            <div class="image-manipulation">
                <br />
                <div id="Update-Picture" style="display: none;"></div>
                <input type="file" name="Image-File">
                <button id="picture-update" onclick="submitLimit()" class="btn btn-default" name="Update-Picture">Update Picture</button>
                <button id="picture-remove" onclick="submitLimit()" class="btn btn-default" name="Remove-Picture">Remove Picture</button>
            </div>
        </div>
        <hr />
        <div class="post-wrapper">
            <label typeof="string">Name : </label><br />
            <textarea class="Form-Field form-control" rows="1" name="NameInput">{{ current.title }}</textarea><br />
            <label typeof="string">Content : </label><br />
            <textarea class="Form-Field form-control" rows="10" name="ContentInput" style="overflow-y: auto; overflow-x: hidden; resize: none; ">{{ current.content }}</textarea><br />
            <button id="submit-form" onclick="submitLimit()" class="btn btn-default">Submit</button>
        </div>
    </form>
    <br />
</div>
<script type="text/javascript" src={{ url_for('static', filename='scripts/update_post_script.js') }}></script>
{% endblock %}

templates/update_user.html
{% extends "base_layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='base_form_style.css') }}" />
{% endblock %}

{% block body %}
<div class="Form form-group">
    <form method="post">
        <label typeof="string">Username : </label><br />
        {% if current.user_name != 'admin' %}
        <input class="form-control" typeof="string" name="UserNameInput" value="{{ current.user_name }}" /><br />
        {% else %}
        <input class="form-control" typeof="string" name="UserNameInput" value="{{ current.user_name }}" readonly="readonly" /><br />
        {% endif %}
        <label typeof="string">Email : </label><br />
        <input class="form-control" typeof="string" name="UserEmailInput" value="{{ current.user_email }}" /><br />
        <label typeof="string">Password : </label><br />
        <input class="form-control" type="password" name="UserPassInput" /><br />
        <button class="btn btn-default">Submit</button>
    </form>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <p class="text-left">{{ message }}</p>
    {% endfor %}
    {% endif %}
    {% endwith %}
</div>
{% endblock %}

templates/user_statistics.html
{% extends "base_layout.html" %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='user_statistics_style.css') }}" />
{% endblock %}

{% block body %}
<body>
    <h3>Posting Statistics</h3>
</body>
<form method="get">
    <label for="Users">Select by User:</label>
    <select name="Users" class="form-control form-control-lg" id="users" onchange="this.form.submit()">
        <option>{{ 'All Users' }}</option>
        {% for user in users %}
        {% if user.user_name == request.args["Users"] %}
        <option selected="selected">{{ user.user_name }}</option>
        {% else %}
        <option>{{ user.user_name }}</option>
        {% endif %}
        {% endfor %}
    </select>
</form>
{% for year, months in stats.items()|reverse %}
<div class="panel panel-default">
    <div class="panel-body">
        <hr />
        <div class="internal-container">
            <p>Posting Year: {{ year }}</p>
            {% for month, total_posts in months.items() %}
            <p><b>{{ month }}</b> : {{total_posts}} Posts</p>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/view_post.html
{% extends "base_layout.html" %}
{% block head %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='view_post_style.css') }}" />
<meta name="id" content="{{ current.post_id }}" />
{% endblock %}
{% block body %}
    <div>
        <p id="Article_Title" onclick='loadData({{ current.post_id|string }})' class="h4"> Article Title : </p><br />
        <p id="Article_Author" class="h5"> Article Author : </p><br />
        <p id="Created_Datetime"> Created : </p>
        <p id="Edited_Datetime"> Edited: </p>
    </div>
    <div class="container">
        <div>
            <img id="Article_Image" width="600" height="300">
        </div>
        <div>
            <textarea id="Article_Content"></textarea>
        </div>
    </div>
    <div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <p class="text-left">{{ message }}</p>
        {% endfor %}
        {% endif %}
        {% endwith %}
    </div>
    {% if session['logged_name'] == current.author or session['logged_name'] == 'admin' %}
    <div class="FooterButtons">
        <div class="btn btn-default"><a href="{{ url_for('.update_item', post_index=current.post_id) }}">Edit</a></div>
        <div class="btn btn-default" id="RemoveBtId"><a href="{{ url_for('.remove_item', post_index=current.post_id) }}" onclick="return OnRemoveClick()">Remove</a></div>
    </div>
    {% endif %}
    <script type="text/javascript" src={{ url_for('static', filename='scripts/post_script.js') }}></script>
{% endblock %}

templates/view_user.html
{% extends "base_layout.html" %}

{% block body %}
<br />
<hr />
<dl class="UserDisplay">
    <dt class="col-sm-3">Username: </dt>
    <dd class="col-sm-9">{{ element.user_name }}</dd>
    <dt class="col-sm-3">Email: </dt>
    <dd class="col-sm-9">{{ element.user_email }}</dd>
    <dt class="col-sm-3">Created on: </dt>
    <dd class="col-sm-9">{{ element.user_timestamp.creation_time }}</dd>
    <dt class="col-sm-3">Last edited on: </dt>
    <dd class="col-sm-9">{{ element.user_timestamp.edit_time }}</dd>
</dl>
{% if element.user_name != 'admin' and (session['logged_name'] == 'admin' or session['logged_name'] == element.user_name) %}
<div class="btn btn-default"><a href="{{ url_for('.update_item', user_index=element.user_id) }}">Edit</a></div>
<div class="btn btn-default"><a href="{{ url_for('.remove_item', user_index=element.user_id) }}">Remove</a></div>
{% endif %}
{% endblock %}